# Generated by Django 4.1.7 on 2023-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordid', models.IntegerField(db_column='wordId')),
                ('wordsource', models.TextField(db_column='wordsource')),
            ],
            options={
                'db_table': 'wordAuthors',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('wordid', models.AutoField(db_column='wordId', primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('translation', models.TextField()),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
