# Generated by Django 4.1.7 on 2023-04-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project_inside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordauthors',
            name='wordid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wordauthors',
            name='wordsource',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='words',
            name='wordid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
